// Generated by packages/contracts/scripts/generate-http-contracts.mjs. Do not edit.
import Ajv from "ajv";
import type { JsonValue } from "./json-value";
import type { Page } from "./pagination";

export interface Failure {
  code: string;
  message: string;
  retryable: boolean;
  cause:
    | "validation"
    | "tool"
    | "runtime"
    | "approval"
    | "cancelled"
    | "timeout"
    | "internal";
  details: JsonValue;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  status: "pending" | "active" | "completed" | "failed" | "cancelled";
  created_at: string;
  failure: Failure | null;
}

export interface Run {
  id: string;
  task_id: string;
  status:
    | "queued"
    | "running"
    | "waiting_for_approval"
    | "waiting_for_delegation"
    | "waiting_for_workflow"
    | "succeeded"
    | "failed"
    | "cancelled";
  created_at: string;
  failure: Failure | null;
  execution_id: string;
}

export interface RunStep {
  id: string;
  run_id: string;
  name: string;
  position: number;
  status:
    | "pending"
    | "running"
    | "waiting_for_approval"
    | "succeeded"
    | "failed"
    | "skipped"
    | "cancelled";
  failure: Failure | null;
}

export interface ApprovalRequest {
  approval_id: string;
  run_id: string | null;
  step_id: string | null;
  category:
    | "tool_execution"
    | "filesystem_write"
    | "network_access"
    | "computer_use"
    | "external_communication"
    | "other";
  summary: string;
  reason: string;
  requested_action: string;
  requested_input: JsonValue;
  status: "pending" | "approved" | "rejected" | "cancelled" | "expired";
  requested_at: string;
  expires_at: string | null;
  resolved_at: string | null;
  resolution_note: string | null;
  resolver: string | null;
  authorization_fingerprint: string | null;
  consumed_at: string | null;
  subject_kind: "run" | "skill_promotion" | "skill_rollback";
  subject_id: string;
}

export interface ToolInvocation {
  invocation_id: string;
  run_id: string;
  step_id: string | null;
  tool_name: string;
  status: "requested" | "running" | "succeeded" | "failed" | "cancelled";
  requested_at: string;
  approval_request_id: string | null;
  output: JsonValue;
  output_set: boolean;
  failure: Failure | null;
}

export interface Artifact {
  artifact_id: string;
  run_id: string;
  step_id: string | null;
  kind: "text" | "file" | "directory" | "url" | "json" | "image" | "other";
  name: string;
  media_type: string;
  location: string;
  created_at: string;
  size: number | null;
  checksum: string | null;
  metadata: JsonValue;
}

export interface RunEvent {
  event_id: string;
  run_id: string;
  step_id: string | null;
  type:
    | "run_created"
    | "run_started"
    | "run_waiting_for_approval"
    | "run_waiting_for_delegation"
    | "run_resumed"
    | "run_succeeded"
    | "run_failed"
    | "run_cancelled"
    | "step_created"
    | "step_started"
    | "step_succeeded"
    | "step_failed"
    | "step_skipped"
    | "step_cancelled"
    | "approval_requested"
    | "approval_resolved"
    | "tool_invocation_requested"
    | "tool_invocation_started"
    | "tool_invocation_succeeded"
    | "tool_invocation_failed"
    | "tool_invocation_cancelled"
    | "artifact_created"
    | "agent_finished"
    | "delegation_dispatched"
    | "delegation_succeeded"
    | "delegation_failed"
    | "delegation_cancelled"
    | "memory_context_attached"
    | "memory_retrieval_degraded"
    | "memory_write_requested"
    | "memory_write_committed"
    | "memory_write_conflicted"
    | "memory_index_marked_stale";
  sequence: number;
  occurred_at: string;
  payload: JsonValue;
}

export interface TaskEvent {
  event_id: string;
  task_id: string;
  type: "task_completed" | "task_failed" | "task_cancelled";
  sequence: number;
  occurred_at: string;
  payload: JsonValue;
}

export interface Schedule {
  id: string;
  task_id: string;
  kind: "once" | "cron";
  cron: string | null;
  run_at: string | null;
  timezone: string;
  status: "active" | "paused" | "completed" | "cancelled";
  next_fire_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ScheduleFire {
  id: string;
  schedule_id: string;
  scheduled_for: string;
  fired_at: string;
  run_id: string;
}

export interface ScheduleDeliveryPolicy {
  schedule_id: string;
  route: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface StartRunResponse {
  task_id: string;
  run_id: string;
}

export interface Conversation {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface ConversationTurn {
  id: string;
  conversation_id: string;
  client_turn_id: string;
  input_text: string;
  input_mode: "typed" | "push_to_talk" | "hands_free";
  recognition_language: string | null;
  task_id: string;
  run_id: string;
  created_at: string;
}

export interface RunResult {
  summary: string | null;
  details: JsonValue;
}

export interface Agent {
  id: string;
  key: string;
  display_name: string;
  description: string;
  status: "active" | "disabled" | "archived";
  active_revision_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface Workflow {
  id: string;
  key: string;
  display_name: string;
  description: string;
  status: "active" | "disabled" | "archived";
  active_revision_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface WorkflowNode {
  id: string;
  revision_id: string;
  node_key: string;
  target_agent_id: string;
  objective: string;
  input_payload: JsonValue;
  expected_output_contract: string;
  created_at: string;
}

export interface WorkflowEdge {
  id: string;
  revision_id: string;
  from: string;
  to: string;
  created_at: string;
}

export interface WorkflowRevision {
  id: string;
  workflow_id: string;
  version: number;
  content_sha256: string;
  source_kind: "operator" | "imported";
  nodes: Array<WorkflowNode>;
  edges: Array<WorkflowEdge>;
  created_at: string;
}

export interface WorkflowExecutionInspection {
  root_run_id: string;
  workflow_execution_id: string;
  workflow_id: string;
  workflow_revision_id: string;
  workflow_revision_sha256: string;
  status: string;
  started_at: string;
  completed_at: string | null;
  failure_code: string | null;
  failure_message: string | null;
}

export interface WorkflowNodeExecutionInspection {
  node_execution_id: string;
  node_key: string;
  target_agent_id: string;
  target_agent_revision_id: string;
  target_agent_revision_sha256: string;
  status: string;
  child_task_id: string | null;
  child_run_id: string | null;
  child_execution_id: string | null;
  result_payload: JsonValue;
  failure_code: string | null;
  failure_message: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
}

export interface AgentRevision {
  id: string;
  agent_id: string;
  version: number;
  instructions: string;
  runtime_kind: string;
  runtime_config: JsonValue;
  content_sha256: string;
  source_kind: "operator" | "imported";
  created_at: string;
}

export interface TaskAgentBinding {
  task_id: string;
  agent_id: string;
  created_at: string;
}

export interface TaskWorkflowBinding {
  task_id: string;
  workflow_id: string;
  created_at: string;
  updated_at: string;
}

export interface RunAgentResolution {
  run_id: string;
  resolved: boolean;
  resolved_at: string | null;
  agent_id: string | null;
  revision_id: string | null;
}

export interface DelegationRequest {
  id: string;
  parent_run_id: string;
  parent_run_step_id: string | null;
  target_agent_id: string;
  objective: string;
  input_payload: JsonValue;
  expected_output_contract: string;
  authorization_fingerprint: string;
  status: "requested" | "dispatched" | "succeeded" | "failed" | "cancelled";
  child_task_id: string | null;
  child_run_id: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
  failure_code: string | null;
}

export interface Skill {
  id: string;
  key: string;
  display_name: string;
  description: string;
  status: "active" | "disabled" | "archived";
  active_revision_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface SkillRevision {
  id: string;
  skill_id: string;
  version: number;
  instructions: string;
  content_sha256: string;
  source_kind: "operator" | "imported";
  created_at: string;
}

export interface TaskSkillBinding {
  task_id: string;
  skill_id: string;
  position: number;
  created_at: string;
}

export interface RunSkillAuditItem {
  skill_id: string;
  skill_key: string;
  revision_id: string;
  version: number;
  instructions: string;
  content_sha256: string;
  source_kind: "operator" | "imported" | "generated";
  position: number;
}

export interface RunSkillBinding {
  run_id: string;
  resolved: boolean;
  resolved_at: string | null;
  items: Array<RunSkillAuditItem>;
}

export interface SkillUsageRecord {
  id: string;
  run_id: string;
  task_id: string;
  skill_id: string;
  revision_id: string;
  position: number;
  resolution_id: string;
  execution_id: string;
  attempt_number: number;
  started_at: string | null;
  outcome: "succeeded" | "failed" | "cancelled" | "resolution_failed";
  failure_code: string | null;
  tool_call_count: number;
  approval_count: number;
  duration_ms: number | null;
  completed_at: string;
  created_at: string;
}

export interface SkillFeedback {
  id: string;
  run_id: string;
  skill_id: string;
  revision_id: string;
  rating: "helpful" | "neutral" | "harmful";
  note: string;
  created_by: string;
  created_at: string;
}

export interface SkillEvidenceSnapshot {
  id: string;
  skill_id: string;
  base_revision_id: string;
  content_sha256: string;
  evidence: Record<string, never>;
  created_at: string;
}

export interface ImprovementProposal {
  id: string;
  skill_id: string;
  base_revision_id: string;
  status:
    | "draft"
    | "ready_for_evaluation"
    | "evaluating"
    | "ready_for_review"
    | "approved"
    | "rejected"
    | "superseded"
    | "cancelled"
    | "expired"
    | "promoted";
  evidence_snapshot_id: string;
  evidence_snapshot_hash: string;
  proposed_instructions: string;
  proposed_content_sha256: string;
  rationale: string;
  generator_version: string;
  created_at: string;
}

export interface EvaluationCase {
  id: string;
  suite_id: string;
  position: number;
  input: string;
  expected_properties: Record<string, never>;
  grading_kind:
    | "exact_match"
    | "contains_all"
    | "contains_none"
    | "json_schema"
    | "required_keys"
    | "tool_proposal_shape";
  created_at: string;
  updated_at: string;
}

export interface EvaluationSuite {
  id: string;
  skill_id: string;
  name: string;
  description: string;
  status: "active" | "disabled";
  created_at: string;
  updated_at: string;
  cases: Array<EvaluationCase>;
}

export interface EvaluationCaseResult {
  evaluation_run_id: string;
  case_id: string;
  status: "succeeded" | "failed";
  score: number;
  reason_code: string | null;
  bounded_details: string;
  output_sha256: string;
}

export interface EvaluationRun {
  id: string;
  suite_id: string;
  skill_id: string;
  revision_id: string | null;
  proposal_id: string | null;
  status: "succeeded" | "failed";
  aggregate_result: Record<string, never>;
  runtime_fingerprint: string;
  target_content_sha256: string;
  runtime_metadata: Record<string, never>;
  suite_snapshot: Record<string, never>;
  case_results: Array<EvaluationCaseResult>;
}

export interface CandidateEvaluation {
  id: string;
  proposal_id: string;
  baseline_evaluation_run_id: string;
  candidate_evaluation_run_id: string;
  comparison_policy_version: string;
  result: "better" | "worse" | "equivalent" | "mixed" | "inconclusive";
  recommendation: "eligible" | "not_eligible" | "requires_manual_override";
  score_delta: number;
  regression_count: number;
  improvement_count: number;
  inconclusive_count: number;
  report_sha256: string;
  comparison_report: Record<string, never>;
}

export interface SkillPromotion {
  id: string;
  proposal_id: string;
  skill_id: string;
  status:
    "pending" | "approved" | "rejected" | "stale" | "cancelled" | "promoted";
  authorization_fingerprint: string;
  target_version: number;
  promoted_revision_id: string | null;
  approval_request_id: string | null;
  candidate_instructions: string;
  candidate_sha256: string;
  evidence_snapshot_id: string;
  evidence_snapshot_hash: string;
  comparison_report: Record<string, never>;
  recommendation: string;
}

export interface SkillRollback {
  id: string;
  skill_id: string;
  expected_current_revision_id: string;
  target_revision_id: string;
  reason: string;
  status:
    "pending" | "approved" | "rejected" | "stale" | "cancelled" | "completed";
  authorization_fingerprint: string;
  approval_request_id: string | null;
  resolved_at: string | null;
  resolver: string | null;
}

export interface SkillImprovementPolicy {
  skill_id: string;
  enabled: boolean;
  minimum_usage_records: number;
  minimum_failures: number;
  minimum_harmful_feedback: number;
  evaluation_suite_id: string;
  cooldown_seconds: number;
  max_open_proposals: JsonValue;
  evidence_window_size: number;
  generator_version: string;
  comparison_policy_version: string;
  last_triggered_at: string | null;
}

export type TaskStatus = Task["status"];
export type RunStatus = Run["status"];
export type RunStepStatus = RunStep["status"];
export type ApprovalCategory = ApprovalRequest["category"];
export type ApprovalStatus = ApprovalRequest["status"];
export type ToolInvocationStatus = ToolInvocation["status"];
export type ArtifactKind = Artifact["kind"];
export type RunEventType = RunEvent["type"];
export type TaskEventType = TaskEvent["type"];

export type WorkflowPage = Page<Workflow>;
export type AgentPage = Page<Agent>;
export type SkillPage = Page<Skill>;
export type TaskPage = Page<Task>;
export type RunPage = Page<Run>;
export type StepPage = Page<RunStep>;
export type ApprovalPage = Page<ApprovalRequest>;
export type InvocationPage = Page<ToolInvocation>;
export type ArtifactPage = Page<Artifact>;
export type RunEventPage = Page<RunEvent>;
export type TaskEventPage = Page<TaskEvent>;
export type SchedulePage = Page<Schedule>;
export type ScheduleFirePage = Page<ScheduleFire>;
export type ConversationTurnPage = Page<ConversationTurn>;

export type WireValidator = (value: unknown, path: string) => void;
export class WireFormatError extends Error {
  constructor(
    readonly path: string,
    readonly issues: string,
  ) {
    super(
      `Response for ${path} does not match the v1 HTTP wire contract: ${issues}`,
    );
    this.name = "WireFormatError";
  }
}

const schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.friday-agent-os.dev/v1/http/responses.json",
  title: "Friday v1 HTTP responses",
  definitions: {
    Failure: {
      type: "object",
      additionalProperties: false,
      required: ["code", "message", "retryable", "cause", "details"],
      properties: {
        code: {
          type: "string",
        },
        message: {
          type: "string",
        },
        retryable: {
          type: "boolean",
        },
        cause: {
          enum: [
            "validation",
            "tool",
            "runtime",
            "approval",
            "cancelled",
            "timeout",
            "internal",
          ],
        },
        details: {},
      },
    },
    Task: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "title",
        "description",
        "status",
        "created_at",
        "failure",
      ],
      properties: {
        id: {
          type: "string",
        },
        title: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["pending", "active", "completed", "failed", "cancelled"],
        },
        created_at: {
          type: "string",
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
      },
    },
    Run: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "task_id",
        "status",
        "created_at",
        "failure",
        "execution_id",
      ],
      properties: {
        id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        status: {
          enum: [
            "queued",
            "running",
            "waiting_for_approval",
            "waiting_for_delegation",
            "waiting_for_workflow",
            "succeeded",
            "failed",
            "cancelled",
          ],
        },
        created_at: {
          type: "string",
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
        execution_id: {
          type: "string",
        },
      },
    },
    RunStep: {
      type: "object",
      additionalProperties: false,
      required: ["id", "run_id", "name", "position", "status", "failure"],
      properties: {
        id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        name: {
          type: "string",
        },
        position: {
          type: "integer",
        },
        status: {
          enum: [
            "pending",
            "running",
            "waiting_for_approval",
            "succeeded",
            "failed",
            "skipped",
            "cancelled",
          ],
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
      },
    },
    ApprovalRequest: {
      type: "object",
      additionalProperties: false,
      required: [
        "approval_id",
        "run_id",
        "step_id",
        "category",
        "summary",
        "reason",
        "requested_action",
        "requested_input",
        "status",
        "requested_at",
        "expires_at",
        "resolved_at",
        "resolution_note",
        "resolver",
        "authorization_fingerprint",
        "consumed_at",
        "subject_kind",
        "subject_id",
      ],
      properties: {
        approval_id: {
          type: "string",
        },
        run_id: {
          type: ["string", "null"],
        },
        step_id: {
          type: ["string", "null"],
        },
        category: {
          enum: [
            "tool_execution",
            "filesystem_write",
            "network_access",
            "computer_use",
            "external_communication",
            "other",
          ],
        },
        summary: {
          type: "string",
        },
        reason: {
          type: "string",
        },
        requested_action: {
          type: "string",
        },
        requested_input: {},
        status: {
          enum: ["pending", "approved", "rejected", "cancelled", "expired"],
        },
        requested_at: {
          type: "string",
        },
        expires_at: {
          type: ["string", "null"],
        },
        resolved_at: {
          type: ["string", "null"],
        },
        resolution_note: {
          type: ["string", "null"],
        },
        resolver: {
          type: ["string", "null"],
        },
        authorization_fingerprint: {
          type: ["string", "null"],
        },
        consumed_at: {
          type: ["string", "null"],
        },
        subject_kind: {
          enum: ["run", "skill_promotion", "skill_rollback"],
        },
        subject_id: {
          type: "string",
        },
      },
    },
    ToolInvocation: {
      type: "object",
      additionalProperties: false,
      required: [
        "invocation_id",
        "run_id",
        "step_id",
        "tool_name",
        "status",
        "requested_at",
        "approval_request_id",
        "output",
        "output_set",
        "failure",
      ],
      properties: {
        invocation_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        tool_name: {
          type: "string",
        },
        status: {
          enum: ["requested", "running", "succeeded", "failed", "cancelled"],
        },
        requested_at: {
          type: "string",
        },
        approval_request_id: {
          type: ["string", "null"],
        },
        output: {},
        output_set: {
          type: "boolean",
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
      },
    },
    Artifact: {
      type: "object",
      additionalProperties: false,
      required: [
        "artifact_id",
        "run_id",
        "step_id",
        "kind",
        "name",
        "media_type",
        "location",
        "created_at",
        "size",
        "checksum",
        "metadata",
      ],
      properties: {
        artifact_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        kind: {
          enum: ["text", "file", "directory", "url", "json", "image", "other"],
        },
        name: {
          type: "string",
        },
        media_type: {
          type: "string",
        },
        location: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
        size: {
          type: ["integer", "null"],
        },
        checksum: {
          type: ["string", "null"],
        },
        metadata: {},
      },
    },
    RunEvent: {
      type: "object",
      additionalProperties: false,
      required: [
        "event_id",
        "run_id",
        "step_id",
        "type",
        "sequence",
        "occurred_at",
        "payload",
      ],
      properties: {
        event_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        type: {
          enum: [
            "run_created",
            "run_started",
            "run_waiting_for_approval",
            "run_waiting_for_delegation",
            "run_resumed",
            "run_succeeded",
            "run_failed",
            "run_cancelled",
            "step_created",
            "step_started",
            "step_succeeded",
            "step_failed",
            "step_skipped",
            "step_cancelled",
            "approval_requested",
            "approval_resolved",
            "tool_invocation_requested",
            "tool_invocation_started",
            "tool_invocation_succeeded",
            "tool_invocation_failed",
            "tool_invocation_cancelled",
            "artifact_created",
            "agent_finished",
            "delegation_dispatched",
            "delegation_succeeded",
            "delegation_failed",
            "delegation_cancelled",
            "memory_context_attached",
            "memory_retrieval_degraded",
            "memory_write_requested",
            "memory_write_committed",
            "memory_write_conflicted",
            "memory_index_marked_stale",
          ],
        },
        sequence: {
          type: "integer",
        },
        occurred_at: {
          type: "string",
        },
        payload: {},
      },
    },
    TaskEvent: {
      type: "object",
      additionalProperties: false,
      required: [
        "event_id",
        "task_id",
        "type",
        "sequence",
        "occurred_at",
        "payload",
      ],
      properties: {
        event_id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        type: {
          enum: ["task_completed", "task_failed", "task_cancelled"],
        },
        sequence: {
          type: "integer",
        },
        occurred_at: {
          type: "string",
        },
        payload: {},
      },
    },
    Schedule: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "task_id",
        "kind",
        "cron",
        "run_at",
        "timezone",
        "status",
        "next_fire_at",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        kind: {
          enum: ["once", "cron"],
        },
        cron: {
          type: ["string", "null"],
        },
        run_at: {
          type: ["string", "null"],
        },
        timezone: {
          type: "string",
        },
        status: {
          enum: ["active", "paused", "completed", "cancelled"],
        },
        next_fire_at: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    ScheduleFire: {
      type: "object",
      additionalProperties: false,
      required: ["id", "schedule_id", "scheduled_for", "fired_at", "run_id"],
      properties: {
        id: {
          type: "string",
        },
        schedule_id: {
          type: "string",
        },
        scheduled_for: {
          type: "string",
        },
        fired_at: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
      },
    },
    ScheduleDeliveryPolicy: {
      type: "object",
      additionalProperties: false,
      required: ["schedule_id", "route", "enabled", "created_at", "updated_at"],
      properties: {
        schedule_id: {
          type: "string",
        },
        route: {
          type: "string",
        },
        enabled: {
          type: "boolean",
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    StartRunResponse: {
      type: "object",
      additionalProperties: false,
      required: ["task_id", "run_id"],
      properties: {
        task_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
      },
    },
    Conversation: {
      type: "object",
      additionalProperties: false,
      required: ["id", "created_at", "updated_at"],
      properties: {
        id: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    ConversationTurn: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "conversation_id",
        "client_turn_id",
        "input_text",
        "input_mode",
        "recognition_language",
        "task_id",
        "run_id",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        conversation_id: {
          type: "string",
        },
        client_turn_id: {
          type: "string",
        },
        input_text: {
          type: "string",
        },
        input_mode: {
          enum: ["typed", "push_to_talk", "hands_free"],
        },
        recognition_language: {
          type: ["string", "null"],
        },
        task_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    RunResult: {
      type: "object",
      additionalProperties: false,
      required: ["summary", "details"],
      properties: {
        summary: {
          type: ["string", "null"],
        },
        details: {},
      },
    },
    Agent: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "key",
        "display_name",
        "description",
        "status",
        "active_revision_id",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        key: {
          type: "string",
        },
        display_name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["active", "disabled", "archived"],
        },
        active_revision_id: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    Workflow: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "key",
        "display_name",
        "description",
        "status",
        "active_revision_id",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        key: {
          type: "string",
        },
        display_name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["active", "disabled", "archived"],
        },
        active_revision_id: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    WorkflowNode: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "revision_id",
        "node_key",
        "target_agent_id",
        "objective",
        "input_payload",
        "expected_output_contract",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        revision_id: {
          type: "string",
        },
        node_key: {
          type: "string",
        },
        target_agent_id: {
          type: "string",
        },
        objective: {
          type: "string",
        },
        input_payload: {},
        expected_output_contract: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    WorkflowEdge: {
      type: "object",
      additionalProperties: false,
      required: ["id", "revision_id", "from", "to", "created_at"],
      properties: {
        id: {
          type: "string",
        },
        revision_id: {
          type: "string",
        },
        from: {
          type: "string",
        },
        to: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    WorkflowRevision: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "workflow_id",
        "version",
        "content_sha256",
        "source_kind",
        "nodes",
        "edges",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        workflow_id: {
          type: "string",
        },
        version: {
          type: "integer",
        },
        content_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        source_kind: {
          enum: ["operator", "imported"],
        },
        nodes: {
          type: "array",
          items: {
            $ref: "#/definitions/WorkflowNode",
          },
        },
        edges: {
          type: "array",
          items: {
            $ref: "#/definitions/WorkflowEdge",
          },
        },
        created_at: {
          type: "string",
        },
      },
    },
    WorkflowExecutionInspection: {
      type: "object",
      additionalProperties: false,
      required: [
        "root_run_id",
        "workflow_execution_id",
        "workflow_id",
        "workflow_revision_id",
        "workflow_revision_sha256",
        "status",
        "started_at",
        "completed_at",
        "failure_code",
        "failure_message",
      ],
      properties: {
        root_run_id: {
          type: "string",
        },
        workflow_execution_id: {
          type: "string",
        },
        workflow_id: {
          type: "string",
        },
        workflow_revision_id: {
          type: "string",
        },
        workflow_revision_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        status: {
          type: "string",
        },
        started_at: {
          type: "string",
        },
        completed_at: {
          type: ["string", "null"],
        },
        failure_code: {
          type: ["string", "null"],
        },
        failure_message: {
          type: ["string", "null"],
        },
      },
    },
    WorkflowNodeExecutionInspection: {
      type: "object",
      additionalProperties: false,
      required: [
        "node_execution_id",
        "node_key",
        "target_agent_id",
        "target_agent_revision_id",
        "target_agent_revision_sha256",
        "status",
        "child_task_id",
        "child_run_id",
        "child_execution_id",
        "result_payload",
        "failure_code",
        "failure_message",
        "created_at",
        "started_at",
        "completed_at",
      ],
      properties: {
        node_execution_id: {
          type: "string",
        },
        node_key: {
          type: "string",
        },
        target_agent_id: {
          type: "string",
        },
        target_agent_revision_id: {
          type: "string",
        },
        target_agent_revision_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        status: {
          type: "string",
        },
        child_task_id: {
          type: ["string", "null"],
        },
        child_run_id: {
          type: ["string", "null"],
        },
        child_execution_id: {
          type: ["string", "null"],
        },
        result_payload: {},
        failure_code: {
          type: ["string", "null"],
        },
        failure_message: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        started_at: {
          type: ["string", "null"],
        },
        completed_at: {
          type: ["string", "null"],
        },
      },
    },
    AgentRevision: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "agent_id",
        "version",
        "instructions",
        "runtime_kind",
        "runtime_config",
        "content_sha256",
        "source_kind",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        agent_id: {
          type: "string",
        },
        version: {
          type: "integer",
        },
        instructions: {
          type: "string",
        },
        runtime_kind: {
          type: "string",
        },
        runtime_config: {},
        content_sha256: {
          type: "string",
        },
        source_kind: {
          enum: ["operator", "imported"],
        },
        created_at: {
          type: "string",
        },
      },
    },
    TaskAgentBinding: {
      type: "object",
      additionalProperties: false,
      required: ["task_id", "agent_id", "created_at"],
      properties: {
        task_id: {
          type: "string",
        },
        agent_id: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    TaskWorkflowBinding: {
      type: "object",
      additionalProperties: false,
      required: ["task_id", "workflow_id", "created_at", "updated_at"],
      properties: {
        task_id: {
          type: "string",
        },
        workflow_id: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    RunAgentResolution: {
      type: "object",
      additionalProperties: false,
      required: [
        "run_id",
        "resolved",
        "resolved_at",
        "agent_id",
        "revision_id",
      ],
      properties: {
        run_id: {
          type: "string",
        },
        resolved: {
          type: "boolean",
        },
        resolved_at: {
          type: ["string", "null"],
        },
        agent_id: {
          type: ["string", "null"],
        },
        revision_id: {
          type: ["string", "null"],
        },
      },
    },
    DelegationRequest: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "parent_run_id",
        "parent_run_step_id",
        "target_agent_id",
        "objective",
        "input_payload",
        "expected_output_contract",
        "authorization_fingerprint",
        "status",
        "child_task_id",
        "child_run_id",
        "created_at",
        "started_at",
        "completed_at",
        "failure_code",
      ],
      properties: {
        id: {
          type: "string",
        },
        parent_run_id: {
          type: "string",
        },
        parent_run_step_id: {
          type: ["string", "null"],
        },
        target_agent_id: {
          type: "string",
        },
        objective: {
          type: "string",
        },
        input_payload: {},
        expected_output_contract: {
          type: "string",
        },
        authorization_fingerprint: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        status: {
          enum: ["requested", "dispatched", "succeeded", "failed", "cancelled"],
        },
        child_task_id: {
          type: ["string", "null"],
        },
        child_run_id: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        started_at: {
          type: ["string", "null"],
        },
        completed_at: {
          type: ["string", "null"],
        },
        failure_code: {
          type: ["string", "null"],
        },
      },
    },
    Skill: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "key",
        "display_name",
        "description",
        "status",
        "active_revision_id",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        key: {
          type: "string",
        },
        display_name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["active", "disabled", "archived"],
        },
        active_revision_id: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    SkillRevision: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "skill_id",
        "version",
        "instructions",
        "content_sha256",
        "source_kind",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        version: {
          type: "integer",
        },
        instructions: {
          type: "string",
        },
        content_sha256: {
          type: "string",
        },
        source_kind: {
          enum: ["operator", "imported"],
        },
        created_at: {
          type: "string",
        },
      },
    },
    TaskSkillBinding: {
      type: "object",
      additionalProperties: false,
      required: ["task_id", "skill_id", "position", "created_at"],
      properties: {
        task_id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        position: {
          type: "integer",
          minimum: 1,
          maximum: 16,
        },
        created_at: {
          type: "string",
        },
      },
    },
    RunSkillAuditItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "skill_id",
        "skill_key",
        "revision_id",
        "version",
        "instructions",
        "content_sha256",
        "source_kind",
        "position",
      ],
      properties: {
        skill_id: {
          type: "string",
        },
        skill_key: {
          type: "string",
        },
        revision_id: {
          type: "string",
        },
        version: {
          type: "integer",
          minimum: 1,
        },
        instructions: {
          type: "string",
        },
        content_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        source_kind: {
          enum: ["operator", "imported", "generated"],
        },
        position: {
          type: "integer",
          minimum: 1,
          maximum: 16,
        },
      },
    },
    RunSkillBinding: {
      type: "object",
      additionalProperties: false,
      required: ["run_id", "resolved", "resolved_at", "items"],
      properties: {
        run_id: {
          type: "string",
        },
        resolved: {
          type: "boolean",
        },
        resolved_at: {
          type: ["string", "null"],
        },
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/RunSkillAuditItem",
          },
        },
      },
    },
    SkillUsageRecord: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "run_id",
        "task_id",
        "skill_id",
        "revision_id",
        "position",
        "resolution_id",
        "execution_id",
        "attempt_number",
        "started_at",
        "outcome",
        "failure_code",
        "tool_call_count",
        "approval_count",
        "duration_ms",
        "completed_at",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        revision_id: {
          type: "string",
        },
        position: {
          type: "integer",
          minimum: 1,
          maximum: 16,
        },
        resolution_id: {
          type: "string",
        },
        execution_id: {
          type: "string",
        },
        attempt_number: {
          type: "integer",
          minimum: 1,
        },
        started_at: {
          type: ["string", "null"],
        },
        outcome: {
          enum: ["succeeded", "failed", "cancelled", "resolution_failed"],
        },
        failure_code: {
          type: ["string", "null"],
        },
        tool_call_count: {
          type: "integer",
          minimum: 0,
        },
        approval_count: {
          type: "integer",
          minimum: 0,
        },
        duration_ms: {
          type: ["integer", "null"],
          minimum: 0,
        },
        completed_at: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    SkillFeedback: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "run_id",
        "skill_id",
        "revision_id",
        "rating",
        "note",
        "created_by",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        revision_id: {
          type: "string",
        },
        rating: {
          enum: ["helpful", "neutral", "harmful"],
        },
        note: {
          type: "string",
        },
        created_by: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    SkillEvidenceSnapshot: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "skill_id",
        "base_revision_id",
        "content_sha256",
        "evidence",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        base_revision_id: {
          type: "string",
        },
        content_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        evidence: {
          type: "object",
        },
        created_at: {
          type: "string",
        },
      },
    },
    ImprovementProposal: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "skill_id",
        "base_revision_id",
        "status",
        "evidence_snapshot_id",
        "evidence_snapshot_hash",
        "proposed_instructions",
        "proposed_content_sha256",
        "rationale",
        "generator_version",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        base_revision_id: {
          type: "string",
        },
        status: {
          enum: [
            "draft",
            "ready_for_evaluation",
            "evaluating",
            "ready_for_review",
            "approved",
            "rejected",
            "superseded",
            "cancelled",
            "expired",
            "promoted",
          ],
        },
        evidence_snapshot_id: {
          type: "string",
        },
        evidence_snapshot_hash: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        proposed_instructions: {
          type: "string",
        },
        proposed_content_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        rationale: {
          type: "string",
        },
        generator_version: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    EvaluationCase: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "suite_id",
        "position",
        "input",
        "expected_properties",
        "grading_kind",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        suite_id: {
          type: "string",
        },
        position: {
          type: "integer",
          minimum: 1,
        },
        input: {
          type: "string",
        },
        expected_properties: {
          type: "object",
        },
        grading_kind: {
          enum: [
            "exact_match",
            "contains_all",
            "contains_none",
            "json_schema",
            "required_keys",
            "tool_proposal_shape",
          ],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    EvaluationSuite: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "skill_id",
        "name",
        "description",
        "status",
        "created_at",
        "updated_at",
        "cases",
      ],
      properties: {
        id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["active", "disabled"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
        cases: {
          type: "array",
          minItems: 1,
          items: {
            $ref: "#/definitions/EvaluationCase",
          },
        },
      },
    },
    EvaluationCaseResult: {
      type: "object",
      additionalProperties: false,
      required: [
        "evaluation_run_id",
        "case_id",
        "status",
        "score",
        "reason_code",
        "bounded_details",
        "output_sha256",
      ],
      properties: {
        evaluation_run_id: {
          type: "string",
        },
        case_id: {
          type: "string",
        },
        status: {
          enum: ["succeeded", "failed"],
        },
        score: {
          type: "number",
          minimum: 0,
          maximum: 1,
        },
        reason_code: {
          type: ["string", "null"],
        },
        bounded_details: {
          type: "string",
        },
        output_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
      },
    },
    EvaluationRun: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "suite_id",
        "skill_id",
        "revision_id",
        "proposal_id",
        "status",
        "aggregate_result",
        "runtime_fingerprint",
        "target_content_sha256",
        "runtime_metadata",
        "suite_snapshot",
        "case_results",
      ],
      properties: {
        id: {
          type: "string",
        },
        suite_id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        revision_id: {
          type: ["string", "null"],
        },
        proposal_id: {
          type: ["string", "null"],
        },
        status: {
          enum: ["succeeded", "failed"],
        },
        aggregate_result: {
          type: "object",
        },
        runtime_fingerprint: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        target_content_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        runtime_metadata: {
          type: "object",
        },
        suite_snapshot: {
          type: "object",
        },
        case_results: {
          type: "array",
          items: {
            $ref: "#/definitions/EvaluationCaseResult",
          },
        },
      },
    },
    CandidateEvaluation: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "proposal_id",
        "baseline_evaluation_run_id",
        "candidate_evaluation_run_id",
        "comparison_policy_version",
        "result",
        "recommendation",
        "score_delta",
        "regression_count",
        "improvement_count",
        "inconclusive_count",
        "report_sha256",
        "comparison_report",
      ],
      properties: {
        id: {
          type: "string",
        },
        proposal_id: {
          type: "string",
        },
        baseline_evaluation_run_id: {
          type: "string",
        },
        candidate_evaluation_run_id: {
          type: "string",
        },
        comparison_policy_version: {
          type: "string",
        },
        result: {
          enum: ["better", "worse", "equivalent", "mixed", "inconclusive"],
        },
        recommendation: {
          enum: ["eligible", "not_eligible", "requires_manual_override"],
        },
        score_delta: {
          type: "number",
        },
        regression_count: {
          type: "integer",
          minimum: 0,
        },
        improvement_count: {
          type: "integer",
          minimum: 0,
        },
        inconclusive_count: {
          type: "integer",
          minimum: 0,
        },
        report_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        comparison_report: {
          type: "object",
        },
      },
    },
    SkillPromotion: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "proposal_id",
        "skill_id",
        "status",
        "authorization_fingerprint",
        "target_version",
        "promoted_revision_id",
        "approval_request_id",
        "candidate_instructions",
        "candidate_sha256",
        "evidence_snapshot_id",
        "evidence_snapshot_hash",
        "comparison_report",
        "recommendation",
      ],
      properties: {
        id: {
          type: "string",
        },
        proposal_id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        status: {
          enum: [
            "pending",
            "approved",
            "rejected",
            "stale",
            "cancelled",
            "promoted",
          ],
        },
        authorization_fingerprint: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        target_version: {
          type: "integer",
          minimum: 1,
        },
        promoted_revision_id: {
          type: ["string", "null"],
        },
        approval_request_id: {
          type: ["string", "null"],
        },
        candidate_instructions: {
          type: "string",
        },
        candidate_sha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        evidence_snapshot_id: {
          type: "string",
        },
        evidence_snapshot_hash: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        comparison_report: {
          type: "object",
        },
        recommendation: {
          type: "string",
        },
      },
    },
    SkillRollback: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "skill_id",
        "expected_current_revision_id",
        "target_revision_id",
        "reason",
        "status",
        "authorization_fingerprint",
        "approval_request_id",
        "resolved_at",
        "resolver",
      ],
      properties: {
        id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        expected_current_revision_id: {
          type: "string",
        },
        target_revision_id: {
          type: "string",
        },
        reason: {
          type: "string",
        },
        status: {
          enum: [
            "pending",
            "approved",
            "rejected",
            "stale",
            "cancelled",
            "completed",
          ],
        },
        authorization_fingerprint: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        approval_request_id: {
          type: ["string", "null"],
        },
        resolved_at: {
          type: ["string", "null"],
        },
        resolver: {
          type: ["string", "null"],
        },
      },
    },
    SkillImprovementPolicy: {
      type: "object",
      additionalProperties: false,
      required: [
        "skill_id",
        "enabled",
        "minimum_usage_records",
        "minimum_failures",
        "minimum_harmful_feedback",
        "evaluation_suite_id",
        "cooldown_seconds",
        "max_open_proposals",
        "evidence_window_size",
        "generator_version",
        "comparison_policy_version",
        "last_triggered_at",
      ],
      properties: {
        skill_id: {
          type: "string",
        },
        enabled: {
          type: "boolean",
        },
        minimum_usage_records: {
          type: "integer",
          minimum: 0,
        },
        minimum_failures: {
          type: "integer",
          minimum: 0,
        },
        minimum_harmful_feedback: {
          type: "integer",
          minimum: 0,
        },
        evaluation_suite_id: {
          type: "string",
        },
        cooldown_seconds: {
          type: "integer",
          minimum: 0,
        },
        max_open_proposals: {
          const: 1,
        },
        evidence_window_size: {
          type: "integer",
          minimum: 1,
          maximum: 200,
        },
        generator_version: {
          type: "string",
        },
        comparison_policy_version: {
          type: "string",
        },
        last_triggered_at: {
          type: ["string", "null"],
        },
      },
    },
  },
  responses: {
    task: {
      $ref: "#/definitions/Task",
    },
    run: {
      $ref: "#/definitions/Run",
    },
    runResult: {
      $ref: "#/definitions/RunResult",
    },
    step: {
      $ref: "#/definitions/RunStep",
    },
    approval: {
      $ref: "#/definitions/ApprovalRequest",
    },
    invocation: {
      $ref: "#/definitions/ToolInvocation",
    },
    artifact: {
      $ref: "#/definitions/Artifact",
    },
    runEvent: {
      $ref: "#/definitions/RunEvent",
    },
    taskEvent: {
      $ref: "#/definitions/TaskEvent",
    },
    schedule: {
      $ref: "#/definitions/Schedule",
    },
    scheduleFire: {
      $ref: "#/definitions/ScheduleFire",
    },
    scheduleDeliveryPolicy: {
      $ref: "#/definitions/ScheduleDeliveryPolicy",
    },
    conversation: {
      $ref: "#/definitions/Conversation",
    },
    conversationTurn: {
      $ref: "#/definitions/ConversationTurn",
    },
    agent: {
      $ref: "#/definitions/Agent",
    },
    workflow: {
      $ref: "#/definitions/Workflow",
    },
    workflowPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Workflow",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    workflowRevision: {
      $ref: "#/definitions/WorkflowRevision",
    },
    workflowRevisions: {
      type: "array",
      items: {
        $ref: "#/definitions/WorkflowRevision",
      },
    },
    workflowExecutionInspection: {
      $ref: "#/definitions/WorkflowExecutionInspection",
    },
    workflowNodeExecutionInspection: {
      type: "array",
      items: {
        $ref: "#/definitions/WorkflowNodeExecutionInspection",
      },
    },
    workflowNodeExecutionInspections: {
      type: "array",
      items: {
        $ref: "#/definitions/WorkflowNodeExecutionInspection",
      },
    },
    agentPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Agent",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    agentRevision: {
      $ref: "#/definitions/AgentRevision",
    },
    agentRevisions: {
      type: "array",
      items: {
        $ref: "#/definitions/AgentRevision",
      },
    },
    taskAgentBinding: {
      anyOf: [
        {
          $ref: "#/definitions/TaskAgentBinding",
        },
        {
          type: "null",
        },
      ],
    },
    taskWorkflowBinding: {
      anyOf: [
        {
          $ref: "#/definitions/TaskWorkflowBinding",
        },
        {
          type: "null",
        },
      ],
    },
    runAgentResolution: {
      $ref: "#/definitions/RunAgentResolution",
    },
    delegationRequest: {
      $ref: "#/definitions/DelegationRequest",
    },
    delegationRequests: {
      type: "array",
      items: {
        $ref: "#/definitions/DelegationRequest",
      },
    },
    skill: {
      $ref: "#/definitions/Skill",
    },
    skillRevision: {
      $ref: "#/definitions/SkillRevision",
    },
    skillRevisions: {
      type: "array",
      items: {
        $ref: "#/definitions/SkillRevision",
      },
    },
    taskSkillBindings: {
      type: "array",
      items: {
        $ref: "#/definitions/TaskSkillBinding",
      },
    },
    runSkillBinding: {
      $ref: "#/definitions/RunSkillBinding",
    },
    skillUsage: {
      type: "array",
      items: {
        $ref: "#/definitions/SkillUsageRecord",
      },
    },
    skillFeedback: {
      type: "array",
      items: {
        $ref: "#/definitions/SkillFeedback",
      },
    },
    skillFeedbackItem: {
      $ref: "#/definitions/SkillFeedback",
    },
    skillEvidenceSnapshot: {
      $ref: "#/definitions/SkillEvidenceSnapshot",
    },
    skillImprovementProposal: {
      $ref: "#/definitions/ImprovementProposal",
    },
    skillImprovementProposals: {
      type: "array",
      items: {
        $ref: "#/definitions/ImprovementProposal",
      },
    },
    skillEvaluationSuite: {
      $ref: "#/definitions/EvaluationSuite",
    },
    skillEvaluationSuites: {
      type: "array",
      items: {
        $ref: "#/definitions/EvaluationSuite",
      },
    },
    skillEvaluationRun: {
      $ref: "#/definitions/EvaluationRun",
    },
    skillCandidateEvaluation: {
      $ref: "#/definitions/CandidateEvaluation",
    },
    skillPromotion: {
      $ref: "#/definitions/SkillPromotion",
    },
    skillRollback: {
      $ref: "#/definitions/SkillRollback",
    },
    skillImprovementPolicy: {
      $ref: "#/definitions/SkillImprovementPolicy",
    },
    skillImprovementPolicyRun: {
      type: "object",
      additionalProperties: false,
      required: ["due"],
      properties: {
        due: {
          type: "boolean",
        },
      },
    },
    skillPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Skill",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    taskPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Task",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    runPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Run",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    stepPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/RunStep",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    approvalPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ApprovalRequest",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    invocationPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ToolInvocation",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    artifactPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Artifact",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    runEventPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/RunEvent",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    taskEventPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/TaskEvent",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    schedulePage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Schedule",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    scheduleFirePage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ScheduleFire",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    conversationTurnPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ConversationTurn",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    startRun: {
      $ref: "#/definitions/StartRunResponse",
    },
  },
} as Record<string, unknown>;
delete schema.$schema; // Ajv's default draft accepts this v1 subset.
const ajv = new Ajv({ allErrors: true, strict: false });
ajv.addSchema(schema, "v1-http");
const validators = Object.fromEntries(
  Object.keys((schema.responses ?? {}) as Record<string, unknown>).map(
    (name) => [name, ajv.compile({ $ref: `v1-http#/responses/${name}` })],
  ),
);
function assertWire(name: string, value: unknown, path: string): void {
  const validate = validators[name];
  if (!validate) throw new Error(`Missing wire validator: ${name}`);
  if (!validate(value))
    throw new WireFormatError(path, ajv.errorsText(validate.errors));
}
export const validateTask: WireValidator = (value, path) =>
  assertWire("task", value, path);
export const validateRun: WireValidator = (value, path) =>
  assertWire("run", value, path);
export const validateRunResult: WireValidator = (value, path) =>
  assertWire("runResult", value, path);
export const validateStep: WireValidator = (value, path) =>
  assertWire("step", value, path);
export const validateApproval: WireValidator = (value, path) =>
  assertWire("approval", value, path);
export const validateInvocation: WireValidator = (value, path) =>
  assertWire("invocation", value, path);
export const validateArtifact: WireValidator = (value, path) =>
  assertWire("artifact", value, path);
export const validateRunEvent: WireValidator = (value, path) =>
  assertWire("runEvent", value, path);
export const validateTaskEvent: WireValidator = (value, path) =>
  assertWire("taskEvent", value, path);
export const validateSchedule: WireValidator = (value, path) =>
  assertWire("schedule", value, path);
export const validateScheduleFire: WireValidator = (value, path) =>
  assertWire("scheduleFire", value, path);
export const validateScheduleDeliveryPolicy: WireValidator = (value, path) =>
  assertWire("scheduleDeliveryPolicy", value, path);
export const validateConversation: WireValidator = (value, path) =>
  assertWire("conversation", value, path);
export const validateConversationTurn: WireValidator = (value, path) =>
  assertWire("conversationTurn", value, path);
export const validateAgent: WireValidator = (value, path) =>
  assertWire("agent", value, path);
export const validateWorkflow: WireValidator = (value, path) =>
  assertWire("workflow", value, path);
export const validateWorkflowPage: WireValidator = (value, path) =>
  assertWire("workflowPage", value, path);
export const validateWorkflowRevision: WireValidator = (value, path) =>
  assertWire("workflowRevision", value, path);
export const validateWorkflowRevisions: WireValidator = (value, path) =>
  assertWire("workflowRevisions", value, path);
export const validateWorkflowExecutionInspection: WireValidator = (
  value,
  path,
) => assertWire("workflowExecutionInspection", value, path);
export const validateWorkflowNodeExecutionInspection: WireValidator = (
  value,
  path,
) => assertWire("workflowNodeExecutionInspection", value, path);
export const validateWorkflowNodeExecutionInspections: WireValidator = (
  value,
  path,
) => assertWire("workflowNodeExecutionInspections", value, path);
export const validateAgentPage: WireValidator = (value, path) =>
  assertWire("agentPage", value, path);
export const validateAgentRevision: WireValidator = (value, path) =>
  assertWire("agentRevision", value, path);
export const validateAgentRevisions: WireValidator = (value, path) =>
  assertWire("agentRevisions", value, path);
export const validateTaskAgentBinding: WireValidator = (value, path) =>
  assertWire("taskAgentBinding", value, path);
export const validateTaskWorkflowBinding: WireValidator = (value, path) =>
  assertWire("taskWorkflowBinding", value, path);
export const validateRunAgentResolution: WireValidator = (value, path) =>
  assertWire("runAgentResolution", value, path);
export const validateDelegationRequest: WireValidator = (value, path) =>
  assertWire("delegationRequest", value, path);
export const validateDelegationRequests: WireValidator = (value, path) =>
  assertWire("delegationRequests", value, path);
export const validateSkill: WireValidator = (value, path) =>
  assertWire("skill", value, path);
export const validateSkillRevision: WireValidator = (value, path) =>
  assertWire("skillRevision", value, path);
export const validateSkillRevisions: WireValidator = (value, path) =>
  assertWire("skillRevisions", value, path);
export const validateTaskSkillBindings: WireValidator = (value, path) =>
  assertWire("taskSkillBindings", value, path);
export const validateRunSkillBinding: WireValidator = (value, path) =>
  assertWire("runSkillBinding", value, path);
export const validateSkillUsage: WireValidator = (value, path) =>
  assertWire("skillUsage", value, path);
export const validateSkillFeedback: WireValidator = (value, path) =>
  assertWire("skillFeedback", value, path);
export const validateSkillFeedbackItem: WireValidator = (value, path) =>
  assertWire("skillFeedbackItem", value, path);
export const validateSkillEvidenceSnapshot: WireValidator = (value, path) =>
  assertWire("skillEvidenceSnapshot", value, path);
export const validateSkillImprovementProposal: WireValidator = (value, path) =>
  assertWire("skillImprovementProposal", value, path);
export const validateSkillImprovementProposals: WireValidator = (value, path) =>
  assertWire("skillImprovementProposals", value, path);
export const validateSkillEvaluationSuite: WireValidator = (value, path) =>
  assertWire("skillEvaluationSuite", value, path);
export const validateSkillEvaluationSuites: WireValidator = (value, path) =>
  assertWire("skillEvaluationSuites", value, path);
export const validateSkillEvaluationRun: WireValidator = (value, path) =>
  assertWire("skillEvaluationRun", value, path);
export const validateSkillCandidateEvaluation: WireValidator = (value, path) =>
  assertWire("skillCandidateEvaluation", value, path);
export const validateSkillPromotion: WireValidator = (value, path) =>
  assertWire("skillPromotion", value, path);
export const validateSkillRollback: WireValidator = (value, path) =>
  assertWire("skillRollback", value, path);
export const validateSkillImprovementPolicy: WireValidator = (value, path) =>
  assertWire("skillImprovementPolicy", value, path);
export const validateSkillImprovementPolicyRun: WireValidator = (value, path) =>
  assertWire("skillImprovementPolicyRun", value, path);
export const validateSkillPage: WireValidator = (value, path) =>
  assertWire("skillPage", value, path);
export const validateTaskPage: WireValidator = (value, path) =>
  assertWire("taskPage", value, path);
export const validateRunPage: WireValidator = (value, path) =>
  assertWire("runPage", value, path);
export const validateStepPage: WireValidator = (value, path) =>
  assertWire("stepPage", value, path);
export const validateApprovalPage: WireValidator = (value, path) =>
  assertWire("approvalPage", value, path);
export const validateInvocationPage: WireValidator = (value, path) =>
  assertWire("invocationPage", value, path);
export const validateArtifactPage: WireValidator = (value, path) =>
  assertWire("artifactPage", value, path);
export const validateRunEventPage: WireValidator = (value, path) =>
  assertWire("runEventPage", value, path);
export const validateTaskEventPage: WireValidator = (value, path) =>
  assertWire("taskEventPage", value, path);
export const validateSchedulePage: WireValidator = (value, path) =>
  assertWire("schedulePage", value, path);
export const validateScheduleFirePage: WireValidator = (value, path) =>
  assertWire("scheduleFirePage", value, path);
export const validateConversationTurnPage: WireValidator = (value, path) =>
  assertWire("conversationTurnPage", value, path);
export const validateStartRun: WireValidator = (value, path) =>
  assertWire("startRun", value, path);
