// Generated by packages/contracts/scripts/generate-http-contracts.mjs. Do not edit.
import Ajv from "ajv";
import type { JsonValue } from "./json-value";
import type { Page } from "./pagination";

export interface Failure {
  code: string;
  message: string;
  retryable: boolean;
  cause:
    | "validation"
    | "tool"
    | "runtime"
    | "approval"
    | "cancelled"
    | "timeout"
    | "internal";
  details: JsonValue;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  status: "pending" | "active" | "completed" | "failed" | "cancelled";
  created_at: string;
  failure: Failure | null;
}

export interface Run {
  id: string;
  task_id: string;
  status:
    | "queued"
    | "running"
    | "waiting_for_approval"
    | "succeeded"
    | "failed"
    | "cancelled";
  created_at: string;
  failure: Failure | null;
  execution_id: string;
}

export interface RunStep {
  id: string;
  run_id: string;
  name: string;
  position: number;
  status:
    | "pending"
    | "running"
    | "waiting_for_approval"
    | "succeeded"
    | "failed"
    | "skipped"
    | "cancelled";
  failure: Failure | null;
}

export interface ApprovalRequest {
  approval_id: string;
  run_id: string;
  step_id: string | null;
  category:
    | "tool_execution"
    | "filesystem_write"
    | "network_access"
    | "computer_use"
    | "other";
  summary: string;
  reason: string;
  requested_action: string;
  requested_input: JsonValue;
  status: "pending" | "approved" | "rejected" | "cancelled" | "expired";
  requested_at: string;
  expires_at: string | null;
  resolved_at: string | null;
  resolution_note: string | null;
  resolver: string | null;
  authorization_fingerprint: string | null;
  consumed_at: string | null;
}

export interface ToolInvocation {
  invocation_id: string;
  run_id: string;
  step_id: string | null;
  tool_name: string;
  status: "requested" | "running" | "succeeded" | "failed" | "cancelled";
  requested_at: string;
  approval_request_id: string | null;
  output: JsonValue;
  output_set: boolean;
  failure: Failure | null;
}

export interface Artifact {
  artifact_id: string;
  run_id: string;
  step_id: string | null;
  kind: "text" | "file" | "directory" | "url" | "json" | "image" | "other";
  name: string;
  media_type: string;
  location: string;
  created_at: string;
  size: number | null;
  checksum: string | null;
  metadata: JsonValue;
}

export interface RunEvent {
  event_id: string;
  run_id: string;
  step_id: string | null;
  type:
    | "run_created"
    | "run_started"
    | "run_waiting_for_approval"
    | "run_resumed"
    | "run_succeeded"
    | "run_failed"
    | "run_cancelled"
    | "step_created"
    | "step_started"
    | "step_succeeded"
    | "step_failed"
    | "step_skipped"
    | "step_cancelled"
    | "approval_requested"
    | "approval_resolved"
    | "tool_invocation_requested"
    | "tool_invocation_started"
    | "tool_invocation_succeeded"
    | "tool_invocation_failed"
    | "tool_invocation_cancelled"
    | "artifact_created"
    | "agent_finished"
    | "memory_context_attached"
    | "memory_retrieval_degraded"
    | "memory_write_requested"
    | "memory_write_committed"
    | "memory_write_conflicted"
    | "memory_index_marked_stale";
  sequence: number;
  occurred_at: string;
  payload: JsonValue;
}

export interface TaskEvent {
  event_id: string;
  task_id: string;
  type: "task_completed" | "task_failed" | "task_cancelled";
  sequence: number;
  occurred_at: string;
  payload: JsonValue;
}

export interface Schedule {
  id: string;
  task_id: string;
  kind: "once" | "cron";
  cron: string | null;
  run_at: string | null;
  timezone: string;
  status: "active" | "paused" | "completed" | "cancelled";
  next_fire_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ScheduleFire {
  id: string;
  schedule_id: string;
  scheduled_for: string;
  fired_at: string;
  run_id: string;
}

export interface ScheduleDeliveryPolicy {
  schedule_id: string;
  route: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface StartRunResponse {
  task_id: string;
  run_id: string;
}

export interface Conversation {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface ConversationTurn {
  id: string;
  conversation_id: string;
  client_turn_id: string;
  input_text: string;
  input_mode: "typed" | "push_to_talk" | "hands_free";
  recognition_language: string | null;
  task_id: string;
  run_id: string;
  created_at: string;
}

export interface RunResult {
  summary: string | null;
  details: JsonValue;
}

export interface Skill {
  id: string;
  key: string;
  display_name: string;
  description: string;
  status: "active" | "disabled" | "archived";
  active_revision_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface SkillRevision {
  id: string;
  skill_id: string;
  version: number;
  instructions: string;
  content_sha256: string;
  source_kind: "operator" | "imported";
  created_at: string;
}

export type TaskStatus = Task["status"];
export type RunStatus = Run["status"];
export type RunStepStatus = RunStep["status"];
export type ApprovalCategory = ApprovalRequest["category"];
export type ApprovalStatus = ApprovalRequest["status"];
export type ToolInvocationStatus = ToolInvocation["status"];
export type ArtifactKind = Artifact["kind"];
export type RunEventType = RunEvent["type"];
export type TaskEventType = TaskEvent["type"];

export type SkillPage = Page<Skill>;
export type TaskPage = Page<Task>;
export type RunPage = Page<Run>;
export type StepPage = Page<RunStep>;
export type ApprovalPage = Page<ApprovalRequest>;
export type InvocationPage = Page<ToolInvocation>;
export type ArtifactPage = Page<Artifact>;
export type RunEventPage = Page<RunEvent>;
export type TaskEventPage = Page<TaskEvent>;
export type SchedulePage = Page<Schedule>;
export type ScheduleFirePage = Page<ScheduleFire>;
export type ConversationTurnPage = Page<ConversationTurn>;

export type WireValidator = (value: unknown, path: string) => void;
export class WireFormatError extends Error {
  constructor(
    readonly path: string,
    readonly issues: string,
  ) {
    super(
      `Response for ${path} does not match the v1 HTTP wire contract: ${issues}`,
    );
    this.name = "WireFormatError";
  }
}

const schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.friday-agent-os.dev/v1/http/responses.json",
  title: "Friday v1 HTTP responses",
  definitions: {
    Failure: {
      type: "object",
      additionalProperties: false,
      required: ["code", "message", "retryable", "cause", "details"],
      properties: {
        code: {
          type: "string",
        },
        message: {
          type: "string",
        },
        retryable: {
          type: "boolean",
        },
        cause: {
          enum: [
            "validation",
            "tool",
            "runtime",
            "approval",
            "cancelled",
            "timeout",
            "internal",
          ],
        },
        details: {},
      },
    },
    Task: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "title",
        "description",
        "status",
        "created_at",
        "failure",
      ],
      properties: {
        id: {
          type: "string",
        },
        title: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["pending", "active", "completed", "failed", "cancelled"],
        },
        created_at: {
          type: "string",
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
      },
    },
    Run: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "task_id",
        "status",
        "created_at",
        "failure",
        "execution_id",
      ],
      properties: {
        id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        status: {
          enum: [
            "queued",
            "running",
            "waiting_for_approval",
            "succeeded",
            "failed",
            "cancelled",
          ],
        },
        created_at: {
          type: "string",
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
        execution_id: {
          type: "string",
        },
      },
    },
    RunStep: {
      type: "object",
      additionalProperties: false,
      required: ["id", "run_id", "name", "position", "status", "failure"],
      properties: {
        id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        name: {
          type: "string",
        },
        position: {
          type: "integer",
        },
        status: {
          enum: [
            "pending",
            "running",
            "waiting_for_approval",
            "succeeded",
            "failed",
            "skipped",
            "cancelled",
          ],
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
      },
    },
    ApprovalRequest: {
      type: "object",
      additionalProperties: false,
      required: [
        "approval_id",
        "run_id",
        "step_id",
        "category",
        "summary",
        "reason",
        "requested_action",
        "requested_input",
        "status",
        "requested_at",
        "expires_at",
        "resolved_at",
        "resolution_note",
        "resolver",
        "authorization_fingerprint",
        "consumed_at",
      ],
      properties: {
        approval_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        category: {
          enum: [
            "tool_execution",
            "filesystem_write",
            "network_access",
            "computer_use",
            "other",
          ],
        },
        summary: {
          type: "string",
        },
        reason: {
          type: "string",
        },
        requested_action: {
          type: "string",
        },
        requested_input: {},
        status: {
          enum: ["pending", "approved", "rejected", "cancelled", "expired"],
        },
        requested_at: {
          type: "string",
        },
        expires_at: {
          type: ["string", "null"],
        },
        resolved_at: {
          type: ["string", "null"],
        },
        resolution_note: {
          type: ["string", "null"],
        },
        resolver: {
          type: ["string", "null"],
        },
        authorization_fingerprint: {
          type: ["string", "null"],
        },
        consumed_at: {
          type: ["string", "null"],
        },
      },
    },
    ToolInvocation: {
      type: "object",
      additionalProperties: false,
      required: [
        "invocation_id",
        "run_id",
        "step_id",
        "tool_name",
        "status",
        "requested_at",
        "approval_request_id",
        "output",
        "output_set",
        "failure",
      ],
      properties: {
        invocation_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        tool_name: {
          type: "string",
        },
        status: {
          enum: ["requested", "running", "succeeded", "failed", "cancelled"],
        },
        requested_at: {
          type: "string",
        },
        approval_request_id: {
          type: ["string", "null"],
        },
        output: {},
        output_set: {
          type: "boolean",
        },
        failure: {
          anyOf: [
            {
              $ref: "#/definitions/Failure",
            },
            {
              type: "null",
            },
          ],
        },
      },
    },
    Artifact: {
      type: "object",
      additionalProperties: false,
      required: [
        "artifact_id",
        "run_id",
        "step_id",
        "kind",
        "name",
        "media_type",
        "location",
        "created_at",
        "size",
        "checksum",
        "metadata",
      ],
      properties: {
        artifact_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        kind: {
          enum: ["text", "file", "directory", "url", "json", "image", "other"],
        },
        name: {
          type: "string",
        },
        media_type: {
          type: "string",
        },
        location: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
        size: {
          type: ["integer", "null"],
        },
        checksum: {
          type: ["string", "null"],
        },
        metadata: {},
      },
    },
    RunEvent: {
      type: "object",
      additionalProperties: false,
      required: [
        "event_id",
        "run_id",
        "step_id",
        "type",
        "sequence",
        "occurred_at",
        "payload",
      ],
      properties: {
        event_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        step_id: {
          type: ["string", "null"],
        },
        type: {
          enum: [
            "run_created",
            "run_started",
            "run_waiting_for_approval",
            "run_resumed",
            "run_succeeded",
            "run_failed",
            "run_cancelled",
            "step_created",
            "step_started",
            "step_succeeded",
            "step_failed",
            "step_skipped",
            "step_cancelled",
            "approval_requested",
            "approval_resolved",
            "tool_invocation_requested",
            "tool_invocation_started",
            "tool_invocation_succeeded",
            "tool_invocation_failed",
            "tool_invocation_cancelled",
            "artifact_created",
            "agent_finished",
            "memory_context_attached",
            "memory_retrieval_degraded",
            "memory_write_requested",
            "memory_write_committed",
            "memory_write_conflicted",
            "memory_index_marked_stale",
          ],
        },
        sequence: {
          type: "integer",
        },
        occurred_at: {
          type: "string",
        },
        payload: {},
      },
    },
    TaskEvent: {
      type: "object",
      additionalProperties: false,
      required: [
        "event_id",
        "task_id",
        "type",
        "sequence",
        "occurred_at",
        "payload",
      ],
      properties: {
        event_id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        type: {
          enum: ["task_completed", "task_failed", "task_cancelled"],
        },
        sequence: {
          type: "integer",
        },
        occurred_at: {
          type: "string",
        },
        payload: {},
      },
    },
    Schedule: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "task_id",
        "kind",
        "cron",
        "run_at",
        "timezone",
        "status",
        "next_fire_at",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        task_id: {
          type: "string",
        },
        kind: {
          enum: ["once", "cron"],
        },
        cron: {
          type: ["string", "null"],
        },
        run_at: {
          type: ["string", "null"],
        },
        timezone: {
          type: "string",
        },
        status: {
          enum: ["active", "paused", "completed", "cancelled"],
        },
        next_fire_at: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    ScheduleFire: {
      type: "object",
      additionalProperties: false,
      required: ["id", "schedule_id", "scheduled_for", "fired_at", "run_id"],
      properties: {
        id: {
          type: "string",
        },
        schedule_id: {
          type: "string",
        },
        scheduled_for: {
          type: "string",
        },
        fired_at: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
      },
    },
    ScheduleDeliveryPolicy: {
      type: "object",
      additionalProperties: false,
      required: ["schedule_id", "route", "enabled", "created_at", "updated_at"],
      properties: {
        schedule_id: {
          type: "string",
        },
        route: {
          type: "string",
        },
        enabled: {
          type: "boolean",
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    StartRunResponse: {
      type: "object",
      additionalProperties: false,
      required: ["task_id", "run_id"],
      properties: {
        task_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
      },
    },
    Conversation: {
      type: "object",
      additionalProperties: false,
      required: ["id", "created_at", "updated_at"],
      properties: {
        id: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    ConversationTurn: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "conversation_id",
        "client_turn_id",
        "input_text",
        "input_mode",
        "recognition_language",
        "task_id",
        "run_id",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        conversation_id: {
          type: "string",
        },
        client_turn_id: {
          type: "string",
        },
        input_text: {
          type: "string",
        },
        input_mode: {
          enum: ["typed", "push_to_talk", "hands_free"],
        },
        recognition_language: {
          type: ["string", "null"],
        },
        task_id: {
          type: "string",
        },
        run_id: {
          type: "string",
        },
        created_at: {
          type: "string",
        },
      },
    },
    RunResult: {
      type: "object",
      additionalProperties: false,
      required: ["summary", "details"],
      properties: {
        summary: {
          type: ["string", "null"],
        },
        details: {},
      },
    },
    Skill: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "key",
        "display_name",
        "description",
        "status",
        "active_revision_id",
        "created_at",
        "updated_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        key: {
          type: "string",
        },
        display_name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        status: {
          enum: ["active", "disabled", "archived"],
        },
        active_revision_id: {
          type: ["string", "null"],
        },
        created_at: {
          type: "string",
        },
        updated_at: {
          type: "string",
        },
      },
    },
    SkillRevision: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "skill_id",
        "version",
        "instructions",
        "content_sha256",
        "source_kind",
        "created_at",
      ],
      properties: {
        id: {
          type: "string",
        },
        skill_id: {
          type: "string",
        },
        version: {
          type: "integer",
        },
        instructions: {
          type: "string",
        },
        content_sha256: {
          type: "string",
        },
        source_kind: {
          enum: ["operator", "imported"],
        },
        created_at: {
          type: "string",
        },
      },
    },
  },
  responses: {
    task: {
      $ref: "#/definitions/Task",
    },
    run: {
      $ref: "#/definitions/Run",
    },
    runResult: {
      $ref: "#/definitions/RunResult",
    },
    step: {
      $ref: "#/definitions/RunStep",
    },
    approval: {
      $ref: "#/definitions/ApprovalRequest",
    },
    invocation: {
      $ref: "#/definitions/ToolInvocation",
    },
    artifact: {
      $ref: "#/definitions/Artifact",
    },
    runEvent: {
      $ref: "#/definitions/RunEvent",
    },
    taskEvent: {
      $ref: "#/definitions/TaskEvent",
    },
    schedule: {
      $ref: "#/definitions/Schedule",
    },
    scheduleFire: {
      $ref: "#/definitions/ScheduleFire",
    },
    scheduleDeliveryPolicy: {
      $ref: "#/definitions/ScheduleDeliveryPolicy",
    },
    conversation: {
      $ref: "#/definitions/Conversation",
    },
    conversationTurn: {
      $ref: "#/definitions/ConversationTurn",
    },
    skill: {
      $ref: "#/definitions/Skill",
    },
    skillRevision: {
      $ref: "#/definitions/SkillRevision",
    },
    skillRevisions: {
      type: "array",
      items: {
        $ref: "#/definitions/SkillRevision",
      },
    },
    skillPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Skill",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    taskPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Task",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    runPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Run",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    stepPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/RunStep",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    approvalPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ApprovalRequest",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    invocationPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ToolInvocation",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    artifactPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Artifact",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    runEventPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/RunEvent",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    taskEventPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/TaskEvent",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    schedulePage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/Schedule",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    scheduleFirePage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ScheduleFire",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    conversationTurnPage: {
      type: "object",
      additionalProperties: false,
      required: ["items", "next_cursor"],
      properties: {
        items: {
          type: "array",
          items: {
            $ref: "#/definitions/ConversationTurn",
          },
        },
        next_cursor: {
          type: ["string", "null"],
        },
      },
    },
    startRun: {
      $ref: "#/definitions/StartRunResponse",
    },
  },
} as Record<string, unknown>;
delete schema.$schema; // Ajv's default draft accepts this v1 subset.
const ajv = new Ajv({ allErrors: true, strict: false });
ajv.addSchema(schema, "v1-http");
const validators = Object.fromEntries(
  Object.keys((schema.responses ?? {}) as Record<string, unknown>).map(
    (name) => [name, ajv.compile({ $ref: `v1-http#/responses/${name}` })],
  ),
);
function assertWire(name: string, value: unknown, path: string): void {
  const validate = validators[name];
  if (!validate) throw new Error(`Missing wire validator: ${name}`);
  if (!validate(value))
    throw new WireFormatError(path, ajv.errorsText(validate.errors));
}
export const validateTask: WireValidator = (value, path) =>
  assertWire("task", value, path);
export const validateRun: WireValidator = (value, path) =>
  assertWire("run", value, path);
export const validateRunResult: WireValidator = (value, path) =>
  assertWire("runResult", value, path);
export const validateStep: WireValidator = (value, path) =>
  assertWire("step", value, path);
export const validateApproval: WireValidator = (value, path) =>
  assertWire("approval", value, path);
export const validateInvocation: WireValidator = (value, path) =>
  assertWire("invocation", value, path);
export const validateArtifact: WireValidator = (value, path) =>
  assertWire("artifact", value, path);
export const validateRunEvent: WireValidator = (value, path) =>
  assertWire("runEvent", value, path);
export const validateTaskEvent: WireValidator = (value, path) =>
  assertWire("taskEvent", value, path);
export const validateSchedule: WireValidator = (value, path) =>
  assertWire("schedule", value, path);
export const validateScheduleFire: WireValidator = (value, path) =>
  assertWire("scheduleFire", value, path);
export const validateScheduleDeliveryPolicy: WireValidator = (value, path) =>
  assertWire("scheduleDeliveryPolicy", value, path);
export const validateConversation: WireValidator = (value, path) =>
  assertWire("conversation", value, path);
export const validateConversationTurn: WireValidator = (value, path) =>
  assertWire("conversationTurn", value, path);
export const validateSkill: WireValidator = (value, path) =>
  assertWire("skill", value, path);
export const validateSkillRevision: WireValidator = (value, path) =>
  assertWire("skillRevision", value, path);
export const validateSkillRevisions: WireValidator = (value, path) =>
  assertWire("skillRevisions", value, path);
export const validateSkillPage: WireValidator = (value, path) =>
  assertWire("skillPage", value, path);
export const validateTaskPage: WireValidator = (value, path) =>
  assertWire("taskPage", value, path);
export const validateRunPage: WireValidator = (value, path) =>
  assertWire("runPage", value, path);
export const validateStepPage: WireValidator = (value, path) =>
  assertWire("stepPage", value, path);
export const validateApprovalPage: WireValidator = (value, path) =>
  assertWire("approvalPage", value, path);
export const validateInvocationPage: WireValidator = (value, path) =>
  assertWire("invocationPage", value, path);
export const validateArtifactPage: WireValidator = (value, path) =>
  assertWire("artifactPage", value, path);
export const validateRunEventPage: WireValidator = (value, path) =>
  assertWire("runEventPage", value, path);
export const validateTaskEventPage: WireValidator = (value, path) =>
  assertWire("taskEventPage", value, path);
export const validateSchedulePage: WireValidator = (value, path) =>
  assertWire("schedulePage", value, path);
export const validateScheduleFirePage: WireValidator = (value, path) =>
  assertWire("scheduleFirePage", value, path);
export const validateConversationTurnPage: WireValidator = (value, path) =>
  assertWire("conversationTurnPage", value, path);
export const validateStartRun: WireValidator = (value, path) =>
  assertWire("startRun", value, path);
